#!/usr/bin/env bash
# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

source common.sh

if [[ ! -d fizz ]]; then
  git clone https://github.com/facebookincubator/fizz
  cd "$PKG_DIR/fizz" || die "cd fail"
  git checkout 979b09dbcd0344890692582d4fb5cb97bc7ab21e
fi

cd "$PKG_DIR/fizz/fizz/" || die "cd fail"

cmake . -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR" -DBUILD_TESTS=OFF
make $MAKE_ARGS && make install $MAKE_ARGS
