#!/usr/bin/env bash
# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

source common.sh

if [[ ! -d wangle ]]; then
  git clone https://github.com/facebook/wangle
  cd "$PKG_DIR/wangle" || die "cd fail"
  git checkout 5ad3fbcf378ab50ef52b0bc9cd12d3e9d6fa1e82
  git -c user.name=infra -c user.email=infra@reddit.com cherry-pick 30244f6b13c37f9077643f0a6d495121bf0cd4ee
fi

cd "$PKG_DIR/wangle/wangle/" || die "cd fail"

cmake . -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR" -DBUILD_TESTS=OFF
make $MAKE_ARGS && make install $MAKE_ARGS
